name: department-resources
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - mysql-simple
  - mysql
  - mtl
  - text
  - bytestring
  - time

library:
  source-dirs: src

executables:
  department-resources:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - department-resources